# doxygen.yml
name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        submodules: recursive

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Configure project
      run: cmake -S . -B build

    - name: Generate documentation
      run: cmake --build build --target doc_doxygen

    - name: Add .nojekyll
      run: touch docs/doxygen/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/doxygen/html
        publish_branch: gh-pages
